version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapiSS
    ports:
      - "3100:3100"
    volumes:
      - /project/aivolution-fastapi/secrets.json:/fastapiSS/app/secrets.json
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
volumes:
  mysql_data:
  secrets:
