FROM mysql:8.0

COPY ./init.sql /docker-entrypoint-initdb.d/

ADD ./init.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init.sh
CMD ["sh", "/docker-entrypoint-initdb.d/init.sh"]